### ISSUE TITLE
This project has a license violation, so I will ask for the license notation.

### ISSUE THREAD

**Issue by soranoba** [DavidAlphaFox/aihtml#2]
The `ai_mustache_parser.erl` original code is from bbmustache.
Since bbmustache is MIT licensed, you need to specify the license.

https://github.com/DavidAlphaFox/aihtml/commit/8911ead92f4a0ec9b34361f02afb029590c81815
https://megalodon.jp/2021-1222-0047-48/https://github.com:443/DavidAlphaFox/aihtml/commit/8911ead92f4a0ec9b34361f02afb029590c81815

**Comment by DavidAlphaFox** [comment]
Thanks for your message.
I update the MIT license in this file. 
And thank you for creating the project bbmustache.

Best wishes.
